[package]
name = "d_anime_discord_presence"
version = "0.2.1"
edition = "2021"

[[bin]]
name = "d_anime_discord_presence"
path = "src/main.rs"

[[bin]]
name = "button_probe"
path = "src/bin/button_probe.rs"

[dependencies]
chrono = "0.4.38"
discord-rich-presence = "1.1.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
